#cloud-config
timezone: Europe/London
package_upgrade: true
packages:
- entr
- git
- man-db
- nano
- tmux
- unzip
- wget
- xsel
write_files:
- path: /home/ubuntu/.tmux.conf
- path: /home/ubuntu/.local/bin/demo-terminal.sh
  permissions: '0775'
- path: /home/ubuntu/.local/bin/setup-git.sh
  permissions: '0775'
- path: /home/ubuntu/.local/bin/setup-lcshell.sh
  permissions: '0775'
- path: /home/ubuntu/.local/bin/setup-shell.sh
  permissions: '0775'
runcmd:
- [bash, -c, "mkdir /home/ubuntu/{Applications,Desktop,Documents,Downloads,Library,Movies,Music,Pictures,Public}" ]
- mkdir -p /home/ubuntu/.tmux/plugins/
- git clone https://github.com/tmux-plugins/tpm /home/ubuntu/.tmux/plugins/tpm
- tmux new-session -d -s "setup" "tmux source /home/ubuntu/.tmux.conf; /home/ubuntu/.tmux/plugins/tpm/bin/install_plugins"
- cp /etc/skel/.profile /home/ubuntu
- chown -R ubuntu:ubuntu /home/ubuntu
